# Shortcuts
alias sapt='sudo apt'
alias gpt='cd $GOPATH'
alias ebash='vim ~/.bashrc'
alias ebalias='vim ~/.bash_aliases'
alias rbash='source ~/.bashrc'
alias gs='git status'
alias ga='git add'
alias gc='git commit -s'
alias gca='git commit -s --amend'
alias glol='git log --oneline --decorate'
alias gl='git log'
alias gb='git branch'
alias gco='git checkout'
alias gcob='git checkout -b'
alias grv='git remote -v'
alias gf='git fetch'
alias greb='git rebase'
alias grebi='git rebase -i'
alias swpoff='sudo swapoff -a'
alias p='pwd'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cp='cp -R'
alias gsi='git status --ignored'
alias gcl='git clone'
alias gra='git remote add'
alias grst='git reset --hard'
alias gshow='git show'
alias grebc='git rebase --continue'
alias greba='git rebase --abort'
alias gd='git diff'
alias glp='git log -p'
alias gcpick='git cherry-pick'
alias gcpickc='git cherry-pick --continue'
alias gcpicka='git cherry-pick --abort'
alias vi='vim -O'
alias vim='vim -O'
alias tl='tmux list-sessions'
alias tn='tmux new -s'
alias ta='tmux attach'
alias g='grep --exclude-dir=*out --exclude=tags -nIr'
alias f='find . -name'
alias cts='ctags-exuberant -R *'
alias rmr='rm -rf'
alias t='htop'

# Proxied Commands
#alias go='https_proxy=https://proxy-us.intel.com:911 go'
#alias curl='curl --proxy http://proxy-us.intel.com:911'
